/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Accessibility {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'mobility'?: boolean;
    'vision'?: boolean;
    'hearing'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "mobility",
            "baseName": "mobility",
            "type": "boolean"
        },
        {
            "name": "vision",
            "baseName": "vision",
            "type": "boolean"
        },
        {
            "name": "hearing",
            "baseName": "hearing",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Accessibility.attributeTypeMap;
    }
}

