/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AfsMeta {
    'totalCount'?: number;
    'totalResolvedCount'?: number;
    'totalPendingCount'?: number;
    'totalNamePendingCount'?: number;
    'totalEmailPendingCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number"
        },
        {
            "name": "totalResolvedCount",
            "baseName": "totalResolvedCount",
            "type": "number"
        },
        {
            "name": "totalPendingCount",
            "baseName": "totalPendingCount",
            "type": "number"
        },
        {
            "name": "totalNamePendingCount",
            "baseName": "totalNamePendingCount",
            "type": "number"
        },
        {
            "name": "totalEmailPendingCount",
            "baseName": "totalEmailPendingCount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AfsMeta.attributeTypeMap;
    }
}

