/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AmiChartItem } from './amiChartItem';
import { IdDTO } from './idDTO';

export class AmiChartCreate {
    'items': Array<AmiChartItem>;
    'name': string;
    'jurisdictions': IdDTO;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<AmiChartItem>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "jurisdictions",
            "baseName": "jurisdictions",
            "type": "IdDTO"
        }    ];

    static getAttributeTypeMap() {
        return AmiChartCreate.attributeTypeMap;
    }
}

