/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApplicationMethodsTypeEnum } from './applicationMethodsTypeEnum';
import { PaperApplication } from './paperApplication';

export class ApplicationMethod {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'type': ApplicationMethodsTypeEnum;
    'label'?: string;
    'externalReference'?: string;
    'acceptsPostmarkedApplications'?: boolean;
    'phoneNumber'?: string;
    'paperApplications'?: Array<PaperApplication>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ApplicationMethodsTypeEnum"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "externalReference",
            "baseName": "externalReference",
            "type": "string"
        },
        {
            "name": "acceptsPostmarkedApplications",
            "baseName": "acceptsPostmarkedApplications",
            "type": "boolean"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "paperApplications",
            "baseName": "paperApplications",
            "type": "Array<PaperApplication>"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationMethod.attributeTypeMap;
    }
}

export namespace ApplicationMethod {
}
