/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum ApplicationReviewStatusEnum {
    Pending = <any> 'pending',
    PendingAndValid = <any> 'pendingAndValid',
    Valid = <any> 'valid',
    Duplicate = <any> 'duplicate'
}
