/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum ApplicationMethodsTypeEnum {
    Internal = <any> 'Internal',
    FileDownload = <any> 'FileDownload',
    ExternalLink = <any> 'ExternalLink',
    PaperPickup = <any> 'PaperPickup',
    PoBox = <any> 'POBox',
    LeasingAgent = <any> 'LeasingAgent',
    Referral = <any> 'Referral'
}
