/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ApplicationFlaggedSetPaginationMeta {
    'currentPage': number;
    'itemCount': number;
    'itemsPerPage': number;
    'totalItems': number;
    'totalPages': number;
    'totalFlagged': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currentPage",
            "baseName": "currentPage",
            "type": "number"
        },
        {
            "name": "itemCount",
            "baseName": "itemCount",
            "type": "number"
        },
        {
            "name": "itemsPerPage",
            "baseName": "itemsPerPage",
            "type": "number"
        },
        {
            "name": "totalItems",
            "baseName": "totalItems",
            "type": "number"
        },
        {
            "name": "totalPages",
            "baseName": "totalPages",
            "type": "number"
        },
        {
            "name": "totalFlagged",
            "baseName": "totalFlagged",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationFlaggedSetPaginationMeta.attributeTypeMap;
    }
}

