/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AddressCreate } from './addressCreate';
import { AddressInput } from './addressInput';
import { BooleanInput } from './booleanInput';
import { InputType } from './inputType';
import { TextInput } from './textInput';

export class ApplicationMultiselectQuestionOptionExtraDataInner {
    'type': InputType;
    'key': string;
    'value': AddressCreate;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "InputType"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "AddressCreate"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationMultiselectQuestionOptionExtraDataInner.attributeTypeMap;
    }
}

export namespace ApplicationMultiselectQuestionOptionExtraDataInner {
}
