/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Application } from './application';
import { FlaggedSetStatusEnum } from './flaggedSetStatusEnum';
import { IdDTO } from './idDTO';
import { RuleEnum } from './ruleEnum';

export class ApplicationFlaggedSet {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'resolvingUser': IdDTO;
    'listing': IdDTO;
    'rule': RuleEnum;
    'ruleKey': string;
    'resolvedTime'?: Date;
    'listingId': string;
    'showConfirmationAlert': boolean;
    'status': FlaggedSetStatusEnum;
    'applications': Array<Application>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "resolvingUser",
            "baseName": "resolvingUser",
            "type": "IdDTO"
        },
        {
            "name": "listing",
            "baseName": "listing",
            "type": "IdDTO"
        },
        {
            "name": "rule",
            "baseName": "rule",
            "type": "RuleEnum"
        },
        {
            "name": "ruleKey",
            "baseName": "ruleKey",
            "type": "string"
        },
        {
            "name": "resolvedTime",
            "baseName": "resolvedTime",
            "type": "Date"
        },
        {
            "name": "listingId",
            "baseName": "listingId",
            "type": "string"
        },
        {
            "name": "showConfirmationAlert",
            "baseName": "showConfirmationAlert",
            "type": "boolean"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "FlaggedSetStatusEnum"
        },
        {
            "name": "applications",
            "baseName": "applications",
            "type": "Array<Application>"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationFlaggedSet.attributeTypeMap;
    }
}

export namespace ApplicationFlaggedSet {
}
