/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApplicationMultiselectQuestionOptionExtraDataInner } from './applicationMultiselectQuestionOptionExtraDataInner';

export class ApplicationMultiselectQuestionOption {
    'key': string;
    'checked': boolean;
    'mapPinPosition'?: string;
    'extraData'?: Array<ApplicationMultiselectQuestionOptionExtraDataInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "checked",
            "baseName": "checked",
            "type": "boolean"
        },
        {
            "name": "mapPinPosition",
            "baseName": "mapPinPosition",
            "type": "string"
        },
        {
            "name": "extraData",
            "baseName": "extraData",
            "type": "Array<ApplicationMultiselectQuestionOptionExtraDataInner>"
        }    ];

    static getAttributeTypeMap() {
        return ApplicationMultiselectQuestionOption.attributeTypeMap;
    }
}

