/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Demographic {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'ethnicity'?: string;
    'gender'?: string;
    'sexualOrientation'?: string;
    'howDidYouHear': Array<string>;
    'race': Array<string>;
    'spokenLanguage'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "ethnicity",
            "baseName": "ethnicity",
            "type": "string"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "string"
        },
        {
            "name": "sexualOrientation",
            "baseName": "sexualOrientation",
            "type": "string"
        },
        {
            "name": "howDidYouHear",
            "baseName": "howDidYouHear",
            "type": "Array<string>"
        },
        {
            "name": "race",
            "baseName": "race",
            "type": "Array<string>"
        },
        {
            "name": "spokenLanguage",
            "baseName": "spokenLanguage",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Demographic.attributeTypeMap;
    }
}

