/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Address } from './address';
import { YesNoEnum } from './yesNoEnum';

export class HouseholdMember {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'orderId'?: number;
    'firstName'?: string;
    'middleName'?: string;
    'lastName'?: string;
    'birthMonth'?: string;
    'birthDay'?: string;
    'birthYear'?: string;
    'sameAddress'?: YesNoEnum;
    'relationship'?: string;
    'workInRegion'?: YesNoEnum;
    'householdMemberWorkAddress'?: Address;
    'householdMemberAddress': Address;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "number"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "middleName",
            "baseName": "middleName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "birthMonth",
            "baseName": "birthMonth",
            "type": "string"
        },
        {
            "name": "birthDay",
            "baseName": "birthDay",
            "type": "string"
        },
        {
            "name": "birthYear",
            "baseName": "birthYear",
            "type": "string"
        },
        {
            "name": "sameAddress",
            "baseName": "sameAddress",
            "type": "YesNoEnum"
        },
        {
            "name": "relationship",
            "baseName": "relationship",
            "type": "string"
        },
        {
            "name": "workInRegion",
            "baseName": "workInRegion",
            "type": "YesNoEnum"
        },
        {
            "name": "householdMemberWorkAddress",
            "baseName": "householdMemberWorkAddress",
            "type": "Address"
        },
        {
            "name": "householdMemberAddress",
            "baseName": "householdMemberAddress",
            "type": "Address"
        }    ];

    static getAttributeTypeMap() {
        return HouseholdMember.attributeTypeMap;
    }
}

export namespace HouseholdMember {
}
