/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdDTO } from './idDTO';
import { LanguagesEnum } from './languagesEnum';

export class Jurisdiction {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'name': string;
    'notificationsSignUpUrl'?: string;
    'languages': Array<LanguagesEnum>;
    'multiselectQuestions': Array<IdDTO>;
    'partnerTerms'?: string;
    'publicUrl': string;
    'emailFromAddress': string;
    'rentalAssistanceDefault': string;
    'enablePartnerSettings'?: boolean;
    'enablePartnerDemographics'?: boolean;
    'enableListingOpportunity'?: boolean;
    'enableGeocodingPreferences'?: boolean;
    'enableAccessibilityFeatures': boolean;
    'enableUtilitiesIncluded': boolean;
    'allowSingleUseCodeLogin': boolean;
    'listingApprovalPermissions': Array<Jurisdiction.ListingApprovalPermissionsEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "notificationsSignUpUrl",
            "baseName": "notificationsSignUpUrl",
            "type": "string"
        },
        {
            "name": "languages",
            "baseName": "languages",
            "type": "Array<LanguagesEnum>"
        },
        {
            "name": "multiselectQuestions",
            "baseName": "multiselectQuestions",
            "type": "Array<IdDTO>"
        },
        {
            "name": "partnerTerms",
            "baseName": "partnerTerms",
            "type": "string"
        },
        {
            "name": "publicUrl",
            "baseName": "publicUrl",
            "type": "string"
        },
        {
            "name": "emailFromAddress",
            "baseName": "emailFromAddress",
            "type": "string"
        },
        {
            "name": "rentalAssistanceDefault",
            "baseName": "rentalAssistanceDefault",
            "type": "string"
        },
        {
            "name": "enablePartnerSettings",
            "baseName": "enablePartnerSettings",
            "type": "boolean"
        },
        {
            "name": "enablePartnerDemographics",
            "baseName": "enablePartnerDemographics",
            "type": "boolean"
        },
        {
            "name": "enableListingOpportunity",
            "baseName": "enableListingOpportunity",
            "type": "boolean"
        },
        {
            "name": "enableGeocodingPreferences",
            "baseName": "enableGeocodingPreferences",
            "type": "boolean"
        },
        {
            "name": "enableAccessibilityFeatures",
            "baseName": "enableAccessibilityFeatures",
            "type": "boolean"
        },
        {
            "name": "enableUtilitiesIncluded",
            "baseName": "enableUtilitiesIncluded",
            "type": "boolean"
        },
        {
            "name": "allowSingleUseCodeLogin",
            "baseName": "allowSingleUseCodeLogin",
            "type": "boolean"
        },
        {
            "name": "listingApprovalPermissions",
            "baseName": "listingApprovalPermissions",
            "type": "Array<Jurisdiction.ListingApprovalPermissionsEnum>"
        }    ];

    static getAttributeTypeMap() {
        return Jurisdiction.attributeTypeMap;
    }
}

export namespace Jurisdiction {
    export enum ListingApprovalPermissionsEnum {
        User = <any> 'user',
        Partner = <any> 'partner',
        Admin = <any> 'admin',
        JurisdictionAdmin = <any> 'jurisdictionAdmin'
    }
}
