/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum LanguagesEnum {
    En = <any> 'en',
    Es = <any> 'es',
    Vi = <any> 'vi',
    Zh = <any> 'zh',
    Tl = <any> 'tl'
}
