/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum ListingOrderByKeys {
    MostRecentlyUpdated = <any> 'mostRecentlyUpdated',
    ApplicationDates = <any> 'applicationDates',
    MostRecentlyClosed = <any> 'mostRecentlyClosed',
    MostRecentlyPublished = <any> 'mostRecentlyPublished',
    Name = <any> 'name',
    WaitlistOpen = <any> 'waitlistOpen',
    Status = <any> 'status',
    UnitsAvailable = <any> 'unitsAvailable',
    MarketingType = <any> 'marketingType'
}
