/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Asset } from './asset';
import { ListingEventsTypeEnum } from './listingEventsTypeEnum';

export class ListingEvent {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'type': ListingEventsTypeEnum;
    'startDate'?: Date;
    'startTime'?: Date;
    'endTime'?: Date;
    'url'?: string;
    'note'?: string;
    'label'?: string;
    'assets'?: Asset;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ListingEventsTypeEnum"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date"
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "Date"
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "Date"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Asset"
        }    ];

    static getAttributeTypeMap() {
        return ListingEvent.attributeTypeMap;
    }
}

export namespace ListingEvent {
}
