/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ListingUtilities {
    'water'?: boolean;
    'gas'?: boolean;
    'trash'?: boolean;
    'sewer'?: boolean;
    'electricity'?: boolean;
    'cable'?: boolean;
    'phone'?: boolean;
    'internet'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "water",
            "baseName": "water",
            "type": "boolean"
        },
        {
            "name": "gas",
            "baseName": "gas",
            "type": "boolean"
        },
        {
            "name": "trash",
            "baseName": "trash",
            "type": "boolean"
        },
        {
            "name": "sewer",
            "baseName": "sewer",
            "type": "boolean"
        },
        {
            "name": "electricity",
            "baseName": "electricity",
            "type": "boolean"
        },
        {
            "name": "cable",
            "baseName": "cable",
            "type": "boolean"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "boolean"
        },
        {
            "name": "internet",
            "baseName": "internet",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ListingUtilities.attributeTypeMap;
    }
}

