/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MultiselectQuestion } from './multiselectQuestion';

export class ListingMultiselectQuestion {
    'multiselectQuestions': MultiselectQuestion;
    'ordinal'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "multiselectQuestions",
            "baseName": "multiselectQuestions",
            "type": "MultiselectQuestion"
        },
        {
            "name": "ordinal",
            "baseName": "ordinal",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ListingMultiselectQuestion.attributeTypeMap;
    }
}

