/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ListingFeatures {
    'elevator'?: boolean;
    'wheelchairRamp'?: boolean;
    'serviceAnimalsAllowed'?: boolean;
    'accessibleParking'?: boolean;
    'parkingOnSite'?: boolean;
    'inUnitWasherDryer'?: boolean;
    'laundryInBuilding'?: boolean;
    'barrierFreeEntrance'?: boolean;
    'rollInShower'?: boolean;
    'grabBars'?: boolean;
    'heatingInUnit'?: boolean;
    'acInUnit'?: boolean;
    'hearing'?: boolean;
    'visual'?: boolean;
    'mobility'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "elevator",
            "baseName": "elevator",
            "type": "boolean"
        },
        {
            "name": "wheelchairRamp",
            "baseName": "wheelchairRamp",
            "type": "boolean"
        },
        {
            "name": "serviceAnimalsAllowed",
            "baseName": "serviceAnimalsAllowed",
            "type": "boolean"
        },
        {
            "name": "accessibleParking",
            "baseName": "accessibleParking",
            "type": "boolean"
        },
        {
            "name": "parkingOnSite",
            "baseName": "parkingOnSite",
            "type": "boolean"
        },
        {
            "name": "inUnitWasherDryer",
            "baseName": "inUnitWasherDryer",
            "type": "boolean"
        },
        {
            "name": "laundryInBuilding",
            "baseName": "laundryInBuilding",
            "type": "boolean"
        },
        {
            "name": "barrierFreeEntrance",
            "baseName": "barrierFreeEntrance",
            "type": "boolean"
        },
        {
            "name": "rollInShower",
            "baseName": "rollInShower",
            "type": "boolean"
        },
        {
            "name": "grabBars",
            "baseName": "grabBars",
            "type": "boolean"
        },
        {
            "name": "heatingInUnit",
            "baseName": "heatingInUnit",
            "type": "boolean"
        },
        {
            "name": "acInUnit",
            "baseName": "acInUnit",
            "type": "boolean"
        },
        {
            "name": "hearing",
            "baseName": "hearing",
            "type": "boolean"
        },
        {
            "name": "visual",
            "baseName": "visual",
            "type": "boolean"
        },
        {
            "name": "mobility",
            "baseName": "mobility",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ListingFeatures.attributeTypeMap;
    }
}

