/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListingViews } from './listingViews';

export class ListingsRetrieveParams {
    'view'?: ListingViews;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "view",
            "baseName": "view",
            "type": "ListingViews"
        }    ];

    static getAttributeTypeMap() {
        return ListingsRetrieveParams.attributeTypeMap;
    }
}

export namespace ListingsRetrieveParams {
}
