/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Address } from './address';
import { ApplicationAddressTypeEnum } from './applicationAddressTypeEnum';
import { ApplicationMethod } from './applicationMethod';
import { Asset } from './asset';
import { IdDTO } from './idDTO';
import { ListingEvent } from './listingEvent';
import { ListingFeatures } from './listingFeatures';
import { ListingImage } from './listingImage';
import { ListingMultiselectQuestion } from './listingMultiselectQuestion';
import { ListingUtilities } from './listingUtilities';
import { ListingsStatusEnum } from './listingsStatusEnum';
import { ReviewOrderTypeEnum } from './reviewOrderTypeEnum';
import { Unit } from './unit';
import { UnitsSummarized } from './unitsSummarized';
import { UnitsSummary } from './unitsSummary';

export class Listing {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'additionalApplicationSubmissionNotes'?: string;
    'digitalApplication'?: boolean;
    'commonDigitalApplication'?: boolean;
    'paperApplication'?: boolean;
    'referralOpportunity'?: boolean;
    'accessibility'?: string;
    'amenities'?: string;
    'buildingTotalUnits'?: number;
    'developer'?: string;
    'householdSizeMax'?: number;
    'householdSizeMin'?: number;
    'neighborhood'?: string;
    'petPolicy'?: string;
    'smokingPolicy'?: string;
    'unitsAvailable'?: number;
    'unitAmenities'?: string;
    'servicesOffered'?: string;
    'yearBuilt'?: number;
    'applicationDueDate'?: Date;
    'applicationOpenDate'?: Date;
    'applicationFee'?: string;
    'applicationOrganization'?: string;
    'applicationPickUpAddressOfficeHours'?: string;
    'applicationPickUpAddressType'?: ApplicationAddressTypeEnum;
    'applicationDropOffAddressOfficeHours'?: string;
    'applicationDropOffAddressType'?: ApplicationAddressTypeEnum;
    'applicationMailingAddressType'?: ApplicationAddressTypeEnum;
    'buildingSelectionCriteria'?: string;
    'costsNotIncluded'?: string;
    'creditHistory'?: string;
    'criminalBackground'?: string;
    'depositMin'?: string;
    'depositMax'?: string;
    'depositHelperText'?: string;
    'disableUnitsAccordion'?: boolean;
    'leasingAgentEmail'?: string;
    'leasingAgentName'?: string;
    'leasingAgentOfficeHours'?: string;
    'leasingAgentPhone'?: string;
    'leasingAgentTitle'?: string;
    'name': string;
    'postmarkedApplicationsReceivedByDate'?: Date;
    'programRules'?: string;
    'rentalAssistance'?: string;
    'rentalHistory'?: string;
    'requiredDocuments'?: string;
    'specialNotes'?: string;
    'waitlistCurrentSize'?: number;
    'waitlistMaxSize'?: number;
    'whatToExpect'?: string;
    'status': ListingsStatusEnum;
    'reviewOrderType'?: ReviewOrderTypeEnum;
    'applicationConfig'?: object;
    'displayWaitlistSize': boolean;
    'showWaitlist'?: boolean;
    'reservedCommunityDescription'?: string;
    'reservedCommunityMinAge'?: number;
    'resultLink'?: string;
    'isWaitlistOpen'?: boolean;
    'waitlistOpenSpots'?: number;
    'customMapPin'?: boolean;
    'publishedAt'?: Date;
    'closedAt'?: Date;
    'afsLastRunAt'?: Date;
    'lastApplicationUpdateAt'?: Date;
    'listingMultiselectQuestions'?: Array<ListingMultiselectQuestion>;
    'applicationMethods': Array<ApplicationMethod>;
    'referralApplication'?: ApplicationMethod;
    'assets': Array<Asset>;
    'listingEvents': Array<ListingEvent>;
    'listingsBuildingAddress': Address;
    'listingsApplicationPickUpAddress'?: Address;
    'listingsApplicationDropOffAddress'?: Address;
    'listingsApplicationMailingAddress'?: Address;
    'listingsLeasingAgentAddress'?: Address;
    'listingsBuildingSelectionCriteriaFile'?: Asset;
    'jurisdictions': IdDTO;
    'listingsResult'?: Asset;
    'reservedCommunityTypes'?: IdDTO;
    'listingImages'?: Array<ListingImage>;
    'listingFeatures'?: ListingFeatures;
    'listingUtilities'?: ListingUtilities;
    'units': Array<Unit>;
    'unitsSummarized'?: UnitsSummarized;
    'unitsSummary'?: Array<UnitsSummary>;
    'urlSlug'?: string;
    'requestedChanges'?: string;
    'requestedChangesDate'?: Date;
    'requestedChangesUser'?: IdDTO;
    'isExternal'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "additionalApplicationSubmissionNotes",
            "baseName": "additionalApplicationSubmissionNotes",
            "type": "string"
        },
        {
            "name": "digitalApplication",
            "baseName": "digitalApplication",
            "type": "boolean"
        },
        {
            "name": "commonDigitalApplication",
            "baseName": "commonDigitalApplication",
            "type": "boolean"
        },
        {
            "name": "paperApplication",
            "baseName": "paperApplication",
            "type": "boolean"
        },
        {
            "name": "referralOpportunity",
            "baseName": "referralOpportunity",
            "type": "boolean"
        },
        {
            "name": "accessibility",
            "baseName": "accessibility",
            "type": "string"
        },
        {
            "name": "amenities",
            "baseName": "amenities",
            "type": "string"
        },
        {
            "name": "buildingTotalUnits",
            "baseName": "buildingTotalUnits",
            "type": "number"
        },
        {
            "name": "developer",
            "baseName": "developer",
            "type": "string"
        },
        {
            "name": "householdSizeMax",
            "baseName": "householdSizeMax",
            "type": "number"
        },
        {
            "name": "householdSizeMin",
            "baseName": "householdSizeMin",
            "type": "number"
        },
        {
            "name": "neighborhood",
            "baseName": "neighborhood",
            "type": "string"
        },
        {
            "name": "petPolicy",
            "baseName": "petPolicy",
            "type": "string"
        },
        {
            "name": "smokingPolicy",
            "baseName": "smokingPolicy",
            "type": "string"
        },
        {
            "name": "unitsAvailable",
            "baseName": "unitsAvailable",
            "type": "number"
        },
        {
            "name": "unitAmenities",
            "baseName": "unitAmenities",
            "type": "string"
        },
        {
            "name": "servicesOffered",
            "baseName": "servicesOffered",
            "type": "string"
        },
        {
            "name": "yearBuilt",
            "baseName": "yearBuilt",
            "type": "number"
        },
        {
            "name": "applicationDueDate",
            "baseName": "applicationDueDate",
            "type": "Date"
        },
        {
            "name": "applicationOpenDate",
            "baseName": "applicationOpenDate",
            "type": "Date"
        },
        {
            "name": "applicationFee",
            "baseName": "applicationFee",
            "type": "string"
        },
        {
            "name": "applicationOrganization",
            "baseName": "applicationOrganization",
            "type": "string"
        },
        {
            "name": "applicationPickUpAddressOfficeHours",
            "baseName": "applicationPickUpAddressOfficeHours",
            "type": "string"
        },
        {
            "name": "applicationPickUpAddressType",
            "baseName": "applicationPickUpAddressType",
            "type": "ApplicationAddressTypeEnum"
        },
        {
            "name": "applicationDropOffAddressOfficeHours",
            "baseName": "applicationDropOffAddressOfficeHours",
            "type": "string"
        },
        {
            "name": "applicationDropOffAddressType",
            "baseName": "applicationDropOffAddressType",
            "type": "ApplicationAddressTypeEnum"
        },
        {
            "name": "applicationMailingAddressType",
            "baseName": "applicationMailingAddressType",
            "type": "ApplicationAddressTypeEnum"
        },
        {
            "name": "buildingSelectionCriteria",
            "baseName": "buildingSelectionCriteria",
            "type": "string"
        },
        {
            "name": "costsNotIncluded",
            "baseName": "costsNotIncluded",
            "type": "string"
        },
        {
            "name": "creditHistory",
            "baseName": "creditHistory",
            "type": "string"
        },
        {
            "name": "criminalBackground",
            "baseName": "criminalBackground",
            "type": "string"
        },
        {
            "name": "depositMin",
            "baseName": "depositMin",
            "type": "string"
        },
        {
            "name": "depositMax",
            "baseName": "depositMax",
            "type": "string"
        },
        {
            "name": "depositHelperText",
            "baseName": "depositHelperText",
            "type": "string"
        },
        {
            "name": "disableUnitsAccordion",
            "baseName": "disableUnitsAccordion",
            "type": "boolean"
        },
        {
            "name": "leasingAgentEmail",
            "baseName": "leasingAgentEmail",
            "type": "string"
        },
        {
            "name": "leasingAgentName",
            "baseName": "leasingAgentName",
            "type": "string"
        },
        {
            "name": "leasingAgentOfficeHours",
            "baseName": "leasingAgentOfficeHours",
            "type": "string"
        },
        {
            "name": "leasingAgentPhone",
            "baseName": "leasingAgentPhone",
            "type": "string"
        },
        {
            "name": "leasingAgentTitle",
            "baseName": "leasingAgentTitle",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "postmarkedApplicationsReceivedByDate",
            "baseName": "postmarkedApplicationsReceivedByDate",
            "type": "Date"
        },
        {
            "name": "programRules",
            "baseName": "programRules",
            "type": "string"
        },
        {
            "name": "rentalAssistance",
            "baseName": "rentalAssistance",
            "type": "string"
        },
        {
            "name": "rentalHistory",
            "baseName": "rentalHistory",
            "type": "string"
        },
        {
            "name": "requiredDocuments",
            "baseName": "requiredDocuments",
            "type": "string"
        },
        {
            "name": "specialNotes",
            "baseName": "specialNotes",
            "type": "string"
        },
        {
            "name": "waitlistCurrentSize",
            "baseName": "waitlistCurrentSize",
            "type": "number"
        },
        {
            "name": "waitlistMaxSize",
            "baseName": "waitlistMaxSize",
            "type": "number"
        },
        {
            "name": "whatToExpect",
            "baseName": "whatToExpect",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ListingsStatusEnum"
        },
        {
            "name": "reviewOrderType",
            "baseName": "reviewOrderType",
            "type": "ReviewOrderTypeEnum"
        },
        {
            "name": "applicationConfig",
            "baseName": "applicationConfig",
            "type": "object"
        },
        {
            "name": "displayWaitlistSize",
            "baseName": "displayWaitlistSize",
            "type": "boolean"
        },
        {
            "name": "showWaitlist",
            "baseName": "showWaitlist",
            "type": "boolean"
        },
        {
            "name": "reservedCommunityDescription",
            "baseName": "reservedCommunityDescription",
            "type": "string"
        },
        {
            "name": "reservedCommunityMinAge",
            "baseName": "reservedCommunityMinAge",
            "type": "number"
        },
        {
            "name": "resultLink",
            "baseName": "resultLink",
            "type": "string"
        },
        {
            "name": "isWaitlistOpen",
            "baseName": "isWaitlistOpen",
            "type": "boolean"
        },
        {
            "name": "waitlistOpenSpots",
            "baseName": "waitlistOpenSpots",
            "type": "number"
        },
        {
            "name": "customMapPin",
            "baseName": "customMapPin",
            "type": "boolean"
        },
        {
            "name": "publishedAt",
            "baseName": "publishedAt",
            "type": "Date"
        },
        {
            "name": "closedAt",
            "baseName": "closedAt",
            "type": "Date"
        },
        {
            "name": "afsLastRunAt",
            "baseName": "afsLastRunAt",
            "type": "Date"
        },
        {
            "name": "lastApplicationUpdateAt",
            "baseName": "lastApplicationUpdateAt",
            "type": "Date"
        },
        {
            "name": "listingMultiselectQuestions",
            "baseName": "listingMultiselectQuestions",
            "type": "Array<ListingMultiselectQuestion>"
        },
        {
            "name": "applicationMethods",
            "baseName": "applicationMethods",
            "type": "Array<ApplicationMethod>"
        },
        {
            "name": "referralApplication",
            "baseName": "referralApplication",
            "type": "ApplicationMethod"
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<Asset>"
        },
        {
            "name": "listingEvents",
            "baseName": "listingEvents",
            "type": "Array<ListingEvent>"
        },
        {
            "name": "listingsBuildingAddress",
            "baseName": "listingsBuildingAddress",
            "type": "Address"
        },
        {
            "name": "listingsApplicationPickUpAddress",
            "baseName": "listingsApplicationPickUpAddress",
            "type": "Address"
        },
        {
            "name": "listingsApplicationDropOffAddress",
            "baseName": "listingsApplicationDropOffAddress",
            "type": "Address"
        },
        {
            "name": "listingsApplicationMailingAddress",
            "baseName": "listingsApplicationMailingAddress",
            "type": "Address"
        },
        {
            "name": "listingsLeasingAgentAddress",
            "baseName": "listingsLeasingAgentAddress",
            "type": "Address"
        },
        {
            "name": "listingsBuildingSelectionCriteriaFile",
            "baseName": "listingsBuildingSelectionCriteriaFile",
            "type": "Asset"
        },
        {
            "name": "jurisdictions",
            "baseName": "jurisdictions",
            "type": "IdDTO"
        },
        {
            "name": "listingsResult",
            "baseName": "listingsResult",
            "type": "Asset"
        },
        {
            "name": "reservedCommunityTypes",
            "baseName": "reservedCommunityTypes",
            "type": "IdDTO"
        },
        {
            "name": "listingImages",
            "baseName": "listingImages",
            "type": "Array<ListingImage>"
        },
        {
            "name": "listingFeatures",
            "baseName": "listingFeatures",
            "type": "ListingFeatures"
        },
        {
            "name": "listingUtilities",
            "baseName": "listingUtilities",
            "type": "ListingUtilities"
        },
        {
            "name": "units",
            "baseName": "units",
            "type": "Array<Unit>"
        },
        {
            "name": "unitsSummarized",
            "baseName": "unitsSummarized",
            "type": "UnitsSummarized"
        },
        {
            "name": "unitsSummary",
            "baseName": "unitsSummary",
            "type": "Array<UnitsSummary>"
        },
        {
            "name": "urlSlug",
            "baseName": "urlSlug",
            "type": "string"
        },
        {
            "name": "requestedChanges",
            "baseName": "requestedChanges",
            "type": "string"
        },
        {
            "name": "requestedChangesDate",
            "baseName": "requestedChangesDate",
            "type": "Date"
        },
        {
            "name": "requestedChangesUser",
            "baseName": "requestedChangesUser",
            "type": "IdDTO"
        },
        {
            "name": "isExternal",
            "baseName": "isExternal",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Listing.attributeTypeMap;
    }
}

export namespace Listing {
}
