/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum ListingsStatusEnum {
    Active = <any> 'active',
    Pending = <any> 'pending',
    Closed = <any> 'closed',
    PendingReview = <any> 'pendingReview',
    ChangesRequested = <any> 'changesRequested'
}
