/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MfaType } from './mfaType';

export class Login {
    'email': string;
    'password': string;
    'mfaCode'?: string;
    'mfaType'?: MfaType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "mfaCode",
            "baseName": "mfaCode",
            "type": "string"
        },
        {
            "name": "mfaType",
            "baseName": "mfaType",
            "type": "MfaType"
        }    ];

    static getAttributeTypeMap() {
        return Login.attributeTypeMap;
    }
}

export namespace Login {
}
