/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MultiselectLink } from './multiselectLink';
import { ValidationMethodEnum } from './validationMethodEnum';

export class MultiselectOption {
    'text': string;
    'untranslatedText'?: string;
    'ordinal': number;
    'description'?: string;
    'links'?: Array<MultiselectLink>;
    'collectAddress'?: boolean;
    'validationMethod'?: ValidationMethodEnum;
    'radiusSize'?: number;
    'collectName'?: boolean;
    'collectRelationship'?: boolean;
    'exclusive'?: boolean;
    'mapLayerId'?: string;
    'mapPinPosition'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "untranslatedText",
            "baseName": "untranslatedText",
            "type": "string"
        },
        {
            "name": "ordinal",
            "baseName": "ordinal",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<MultiselectLink>"
        },
        {
            "name": "collectAddress",
            "baseName": "collectAddress",
            "type": "boolean"
        },
        {
            "name": "validationMethod",
            "baseName": "validationMethod",
            "type": "ValidationMethodEnum"
        },
        {
            "name": "radiusSize",
            "baseName": "radiusSize",
            "type": "number"
        },
        {
            "name": "collectName",
            "baseName": "collectName",
            "type": "boolean"
        },
        {
            "name": "collectRelationship",
            "baseName": "collectRelationship",
            "type": "boolean"
        },
        {
            "name": "exclusive",
            "baseName": "exclusive",
            "type": "boolean"
        },
        {
            "name": "mapLayerId",
            "baseName": "mapLayerId",
            "type": "string"
        },
        {
            "name": "mapPinPosition",
            "baseName": "mapPinPosition",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MultiselectOption.attributeTypeMap;
    }
}

export namespace MultiselectOption {
}
