/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MultiselectQuestionsApplicationSectionEnum } from './multiselectQuestionsApplicationSectionEnum';

export class MultiselectQuestionFilterParams {
    '$comparison': MultiselectQuestionFilterParams.ComparisonEnum = MultiselectQuestionFilterParams.ComparisonEnum.Equal;
    'jurisdiction'?: string;
    'applicationSection'?: MultiselectQuestionsApplicationSectionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$comparison",
            "baseName": "$comparison",
            "type": "MultiselectQuestionFilterParams.ComparisonEnum"
        },
        {
            "name": "jurisdiction",
            "baseName": "jurisdiction",
            "type": "string"
        },
        {
            "name": "applicationSection",
            "baseName": "applicationSection",
            "type": "MultiselectQuestionsApplicationSectionEnum"
        }    ];

    static getAttributeTypeMap() {
        return MultiselectQuestionFilterParams.attributeTypeMap;
    }
}

export namespace MultiselectQuestionFilterParams {
    export enum ComparisonEnum {
        Equal = <any> '=',
        NotEqual = <any> '<>',
        In = <any> 'IN',
        GreaterThanOrEqualTo = <any> '>=',
        LessThanOrEqualTo = <any> '<=',
        Na = <any> 'NA'
    }
}
