/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdDTO } from './idDTO';
import { MultiselectLink } from './multiselectLink';
import { MultiselectOption } from './multiselectOption';
import { MultiselectQuestionsApplicationSectionEnum } from './multiselectQuestionsApplicationSectionEnum';

export class MultiselectQuestionCreate {
    'text': string;
    'untranslatedOptOutText'?: string;
    'subText'?: string;
    'description'?: string;
    'links'?: Array<MultiselectLink>;
    'jurisdictions': Array<IdDTO>;
    'options'?: Array<MultiselectOption>;
    'optOutText'?: string;
    'hideFromListing'?: boolean;
    'applicationSection': MultiselectQuestionsApplicationSectionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "untranslatedOptOutText",
            "baseName": "untranslatedOptOutText",
            "type": "string"
        },
        {
            "name": "subText",
            "baseName": "subText",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Array<MultiselectLink>"
        },
        {
            "name": "jurisdictions",
            "baseName": "jurisdictions",
            "type": "Array<IdDTO>"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<MultiselectOption>"
        },
        {
            "name": "optOutText",
            "baseName": "optOutText",
            "type": "string"
        },
        {
            "name": "hideFromListing",
            "baseName": "hideFromListing",
            "type": "boolean"
        },
        {
            "name": "applicationSection",
            "baseName": "applicationSection",
            "type": "MultiselectQuestionsApplicationSectionEnum"
        }    ];

    static getAttributeTypeMap() {
        return MultiselectQuestionCreate.attributeTypeMap;
    }
}

export namespace MultiselectQuestionCreate {
}
