/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApplicationFlaggedSet } from './applicationFlaggedSet';
import { ApplicationFlaggedSetPaginationMeta } from './applicationFlaggedSetPaginationMeta';

export class PaginatedAfsDto {
    'items': Array<ApplicationFlaggedSet>;
    'meta': ApplicationFlaggedSetPaginationMeta;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ApplicationFlaggedSet>"
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "ApplicationFlaggedSetPaginationMeta"
        }    ];

    static getAttributeTypeMap() {
        return PaginatedAfsDto.attributeTypeMap;
    }
}

