/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaginationMeta } from './paginationMeta';
import { User } from './user';

export class PaginatedUserDto {
    'items': Array<User>;
    'meta': PaginationMeta;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<User>"
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "PaginationMeta"
        }    ];

    static getAttributeTypeMap() {
        return PaginatedUserDto.attributeTypeMap;
    }
}

