/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Asset } from './asset';
import { LanguagesEnum } from './languagesEnum';

export class PaperApplication {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'language': LanguagesEnum;
    'assets': Asset;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "LanguagesEnum"
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Asset"
        }    ];

    static getAttributeTypeMap() {
        return PaperApplication.attributeTypeMap;
    }
}

export namespace PaperApplication {
}
