/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdDTO } from './idDTO';
import { UnitAmiChartOverrideCreate } from './unitAmiChartOverrideCreate';

export class UnitCreate {
    'amiPercentage'?: string;
    'annualIncomeMin'?: string;
    'monthlyIncomeMin'?: string;
    'floor'?: number;
    'annualIncomeMax'?: string;
    'maxOccupancy'?: number;
    'minOccupancy'?: number;
    'monthlyRent'?: string;
    'numBathrooms'?: number;
    'numBedrooms'?: number;
    'number'?: string;
    'sqFeet'?: string;
    'monthlyRentAsPercentOfIncome'?: string;
    'bmrProgramChart'?: boolean;
    'unitTypes'?: IdDTO;
    'amiChart'?: IdDTO;
    'unitAccessibilityPriorityTypes'?: IdDTO;
    'unitRentTypes'?: IdDTO;
    'unitAmiChartOverrides'?: UnitAmiChartOverrideCreate;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amiPercentage",
            "baseName": "amiPercentage",
            "type": "string"
        },
        {
            "name": "annualIncomeMin",
            "baseName": "annualIncomeMin",
            "type": "string"
        },
        {
            "name": "monthlyIncomeMin",
            "baseName": "monthlyIncomeMin",
            "type": "string"
        },
        {
            "name": "floor",
            "baseName": "floor",
            "type": "number"
        },
        {
            "name": "annualIncomeMax",
            "baseName": "annualIncomeMax",
            "type": "string"
        },
        {
            "name": "maxOccupancy",
            "baseName": "maxOccupancy",
            "type": "number"
        },
        {
            "name": "minOccupancy",
            "baseName": "minOccupancy",
            "type": "number"
        },
        {
            "name": "monthlyRent",
            "baseName": "monthlyRent",
            "type": "string"
        },
        {
            "name": "numBathrooms",
            "baseName": "numBathrooms",
            "type": "number"
        },
        {
            "name": "numBedrooms",
            "baseName": "numBedrooms",
            "type": "number"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "sqFeet",
            "baseName": "sqFeet",
            "type": "string"
        },
        {
            "name": "monthlyRentAsPercentOfIncome",
            "baseName": "monthlyRentAsPercentOfIncome",
            "type": "string"
        },
        {
            "name": "bmrProgramChart",
            "baseName": "bmrProgramChart",
            "type": "boolean"
        },
        {
            "name": "unitTypes",
            "baseName": "unitTypes",
            "type": "IdDTO"
        },
        {
            "name": "amiChart",
            "baseName": "amiChart",
            "type": "IdDTO"
        },
        {
            "name": "unitAccessibilityPriorityTypes",
            "baseName": "unitAccessibilityPriorityTypes",
            "type": "IdDTO"
        },
        {
            "name": "unitRentTypes",
            "baseName": "unitRentTypes",
            "type": "IdDTO"
        },
        {
            "name": "unitAmiChartOverrides",
            "baseName": "unitAmiChartOverrides",
            "type": "UnitAmiChartOverrideCreate"
        }    ];

    static getAttributeTypeMap() {
        return UnitCreate.attributeTypeMap;
    }
}

