/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UnitRentTypeEnum } from './unitRentTypeEnum';

export class UnitRentTypeCreate {
    'name': UnitRentTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "UnitRentTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return UnitRentTypeCreate.attributeTypeMap;
    }
}

export namespace UnitRentTypeCreate {
}
