/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AmiChartItem } from './amiChartItem';

export class UnitAmiChartOverride {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'items': Array<AmiChartItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<AmiChartItem>"
        }    ];

    static getAttributeTypeMap() {
        return UnitAmiChartOverride.attributeTypeMap;
    }
}

