/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdDTO } from './idDTO';

export class UnitsSummary {
    'id': string;
    'unitTypes': IdDTO;
    'monthlyRentMin'?: number;
    'monthlyRentMax'?: number;
    'monthlyRentAsPercentOfIncome'?: string;
    'amiPercentage'?: number;
    'minimumIncomeMin'?: string;
    'minimumIncomeMax'?: string;
    'maxOccupancy'?: number;
    'minOccupancy'?: number;
    'floorMin'?: number;
    'floorMax'?: number;
    'sqFeetMin'?: string;
    'sqFeetMax'?: string;
    'unitAccessibilityPriorityTypes'?: IdDTO;
    'totalCount'?: number;
    'totalAvailable'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "unitTypes",
            "baseName": "unitTypes",
            "type": "IdDTO"
        },
        {
            "name": "monthlyRentMin",
            "baseName": "monthlyRentMin",
            "type": "number"
        },
        {
            "name": "monthlyRentMax",
            "baseName": "monthlyRentMax",
            "type": "number"
        },
        {
            "name": "monthlyRentAsPercentOfIncome",
            "baseName": "monthlyRentAsPercentOfIncome",
            "type": "string"
        },
        {
            "name": "amiPercentage",
            "baseName": "amiPercentage",
            "type": "number"
        },
        {
            "name": "minimumIncomeMin",
            "baseName": "minimumIncomeMin",
            "type": "string"
        },
        {
            "name": "minimumIncomeMax",
            "baseName": "minimumIncomeMax",
            "type": "string"
        },
        {
            "name": "maxOccupancy",
            "baseName": "maxOccupancy",
            "type": "number"
        },
        {
            "name": "minOccupancy",
            "baseName": "minOccupancy",
            "type": "number"
        },
        {
            "name": "floorMin",
            "baseName": "floorMin",
            "type": "number"
        },
        {
            "name": "floorMax",
            "baseName": "floorMax",
            "type": "number"
        },
        {
            "name": "sqFeetMin",
            "baseName": "sqFeetMin",
            "type": "string"
        },
        {
            "name": "sqFeetMax",
            "baseName": "sqFeetMax",
            "type": "string"
        },
        {
            "name": "unitAccessibilityPriorityTypes",
            "baseName": "unitAccessibilityPriorityTypes",
            "type": "IdDTO"
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number"
        },
        {
            "name": "totalAvailable",
            "baseName": "totalAvailable",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UnitsSummary.attributeTypeMap;
    }
}

