/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum UnitTypeEnum {
    Studio = <any> 'studio',
    OneBdrm = <any> 'oneBdrm',
    TwoBdrm = <any> 'twoBdrm',
    ThreeBdrm = <any> 'threeBdrm',
    FourBdrm = <any> 'fourBdrm',
    Sro = <any> 'SRO',
    FiveBdrm = <any> 'fiveBdrm'
}
