/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MinMax } from './minMax';
import { MinMaxCurrency } from './minMaxCurrency';
import { UnitType } from './unitType';

export class UnitSummary {
    'unitTypes': UnitType;
    'minIncomeRange': MinMaxCurrency;
    'occupancyRange': MinMax;
    'rentAsPercentIncomeRange': MinMax;
    'rentRange': MinMaxCurrency;
    'totalAvailable': number;
    'areaRange': MinMax;
    'floorRange'?: MinMax;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unitTypes",
            "baseName": "unitTypes",
            "type": "UnitType"
        },
        {
            "name": "minIncomeRange",
            "baseName": "minIncomeRange",
            "type": "MinMaxCurrency"
        },
        {
            "name": "occupancyRange",
            "baseName": "occupancyRange",
            "type": "MinMax"
        },
        {
            "name": "rentAsPercentIncomeRange",
            "baseName": "rentAsPercentIncomeRange",
            "type": "MinMax"
        },
        {
            "name": "rentRange",
            "baseName": "rentRange",
            "type": "MinMaxCurrency"
        },
        {
            "name": "totalAvailable",
            "baseName": "totalAvailable",
            "type": "number"
        },
        {
            "name": "areaRange",
            "baseName": "areaRange",
            "type": "MinMax"
        },
        {
            "name": "floorRange",
            "baseName": "floorRange",
            "type": "MinMax"
        }    ];

    static getAttributeTypeMap() {
        return UnitSummary.attributeTypeMap;
    }
}

