/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UserRole {
    'isAdmin'?: boolean;
    'isJurisdictionalAdmin'?: boolean;
    'isPartner'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isAdmin",
            "baseName": "isAdmin",
            "type": "boolean"
        },
        {
            "name": "isJurisdictionalAdmin",
            "baseName": "isJurisdictionalAdmin",
            "type": "boolean"
        },
        {
            "name": "isPartner",
            "baseName": "isPartner",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UserRole.attributeTypeMap;
    }
}

