/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdDTO } from './idDTO';
import { LanguagesEnum } from './languagesEnum';
import { UserRole } from './userRole';

export class UserUpdate {
    'id': string;
    'firstName': string;
    'middleName'?: string;
    'lastName': string;
    'dob'?: Date;
    'phoneNumber'?: string;
    'listings': Array<IdDTO> | null;
    'userRoles'?: UserRole;
    'language'?: LanguagesEnum;
    'agreedToTermsOfService': boolean;
    'email'?: string;
    'newEmail'?: string;
    'password'?: string;
    'currentPassword'?: string;
    'appUrl'?: string;
    'jurisdictions'?: Array<IdDTO>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "middleName",
            "baseName": "middleName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "dob",
            "baseName": "dob",
            "type": "Date"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "listings",
            "baseName": "listings",
            "type": "Array<IdDTO>"
        },
        {
            "name": "userRoles",
            "baseName": "userRoles",
            "type": "UserRole"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "LanguagesEnum"
        },
        {
            "name": "agreedToTermsOfService",
            "baseName": "agreedToTermsOfService",
            "type": "boolean"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "newEmail",
            "baseName": "newEmail",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "currentPassword",
            "baseName": "currentPassword",
            "type": "string"
        },
        {
            "name": "appUrl",
            "baseName": "appUrl",
            "type": "string"
        },
        {
            "name": "jurisdictions",
            "baseName": "jurisdictions",
            "type": "Array<IdDTO>"
        }    ];

    static getAttributeTypeMap() {
        return UserUpdate.attributeTypeMap;
    }
}

export namespace UserUpdate {
}
