/**
 * Bloom API
 * The API for Bloom
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IdDTO } from './idDTO';
import { Jurisdiction } from './jurisdiction';
import { LanguagesEnum } from './languagesEnum';
import { UserRole } from './userRole';

export class User {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'passwordUpdatedAt': Date;
    'passwordValidForDays': number;
    'confirmedAt'?: Date;
    'email': string;
    'firstName': string;
    'middleName'?: string;
    'lastName': string;
    'dob'?: Date;
    'phoneNumber'?: string;
    'listings': Array<IdDTO> | null;
    'userRoles'?: UserRole;
    'language'?: LanguagesEnum;
    'jurisdictions': Array<Jurisdiction>;
    'mfaEnabled'?: boolean;
    'lastLoginAt'?: Date;
    'failedLoginAttemptsCount'?: number;
    'phoneNumberVerified'?: boolean;
    'agreedToTermsOfService': boolean;
    'hitConfirmationURL'?: Date;
    'activeAccessToken'?: string;
    'activeRefreshToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "passwordUpdatedAt",
            "baseName": "passwordUpdatedAt",
            "type": "Date"
        },
        {
            "name": "passwordValidForDays",
            "baseName": "passwordValidForDays",
            "type": "number"
        },
        {
            "name": "confirmedAt",
            "baseName": "confirmedAt",
            "type": "Date"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "middleName",
            "baseName": "middleName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "dob",
            "baseName": "dob",
            "type": "Date"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "listings",
            "baseName": "listings",
            "type": "Array<IdDTO>"
        },
        {
            "name": "userRoles",
            "baseName": "userRoles",
            "type": "UserRole"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "LanguagesEnum"
        },
        {
            "name": "jurisdictions",
            "baseName": "jurisdictions",
            "type": "Array<Jurisdiction>"
        },
        {
            "name": "mfaEnabled",
            "baseName": "mfaEnabled",
            "type": "boolean"
        },
        {
            "name": "lastLoginAt",
            "baseName": "lastLoginAt",
            "type": "Date"
        },
        {
            "name": "failedLoginAttemptsCount",
            "baseName": "failedLoginAttemptsCount",
            "type": "number"
        },
        {
            "name": "phoneNumberVerified",
            "baseName": "phoneNumberVerified",
            "type": "boolean"
        },
        {
            "name": "agreedToTermsOfService",
            "baseName": "agreedToTermsOfService",
            "type": "boolean"
        },
        {
            "name": "hitConfirmationURL",
            "baseName": "hitConfirmationURL",
            "type": "Date"
        },
        {
            "name": "activeAccessToken",
            "baseName": "activeAccessToken",
            "type": "string"
        },
        {
            "name": "activeRefreshToken",
            "baseName": "activeRefreshToken",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
}

export namespace User {
}
